version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: justacms-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=justacms
        - MYSQL_USER=justauser
        - MYSQL_PASSWORD=senha

    webserver:
      image: nginx:alpine
      container_name: justacms-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: justacms-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      links:
        - mysql
