-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 05:11:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema semhora_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema semhora_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `semhora_test` DEFAULT CHARACTER SET utf8 ;
USE `semhora_test` ;

-- -----------------------------------------------------
-- Table `semhora_test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semhora_test`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `login` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semhora_test`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semhora_test`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL,
  `address` VARCHAR(255) NOT NULL,
  `starts_at` DATETIME NOT NULL,
  `ends_at` DATETIME NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `status` TINYINT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_events_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `semhora_test`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `semhora_test`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `semhora_test`;
INSERT INTO `semhora_test`.`users` (`id`, `name`, `login`, `email`, `password`, `created_at`, `updated_at`, `status`) VALUES (1, 'Administrador', 'admin', 'admin@felipefausto.com.br', '6a4e012bd9583858a5a6fa15f58bd86a25af266d3a4344f1ec2018b778f29ba83be86eb45e6dc204e11276f4a99eff4e2144fbe15e756c2c88e999649aae7d94', DEFAULT, NULL, 1);

COMMIT;

