<div class="row">
    <div class="col-md-5 col-md-offset-1">
        <h1>Novo Evento</h1>
        <form method="post" action="/evento/novo" enctype="multipart/form-data">
            <div class="form-group">
                <label for="text">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" required>
            </div>
            <div class="form-group">
                <label for="text">Imagem</label>
                <input type="file" class="form-control" id="img" name="img" required>
            </div>
            <div class="form-group">
                <label for="text">Local</label>
                <input type="text" class="form-control" id="local" name="local" required>
            </div>
            <div class="form-group">
                <label for="descrica">Descrição:</label>
                <textarea class="form-control" rows="5" id="descricao" name="descricao" required></textarea>
            </div>
            <button type="submit" class="btn btn-default">Criar</button>
        </form>
    </div>
</div>