<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="<?php echo GLOBAL_VARS['LINGUAGEM'] ?>">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title><?php echo GLOBAL_VARS['TITULO']?></title>
	
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="<?php echo GLOBAL_VARS['DESCRICAO'] ?>" name="description" />
	<meta content="<?php echo GLOBAL_VARS['AUTOR'] ?>" name="author" />
	
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<link href="<?php echo ASSETS['PLUGINS'] ?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo ASSETS['PLUGINS'] ?>bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<!-- END GLOBAL MANDATORY STYLES -->
	
	<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
	<link href="<?php echo ASSETS['PLUGINS'] ?>fancybox/source/jquery.fancybox.css" rel="stylesheet" />
	<link href="<?php echo ASSETS['CSS'] ?>footer.css" rel="stylesheet" type="text/css" />
	<!-- END PAGE LEVEL PLUGIN STYLES -->
	
	<!-- BEGIN THEME STYLES -->
	<link href="<?php echo ASSETS['CSS'] ?>style-metronic.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo ASSETS['CSS'] ?>style.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo ASSETS['CSS'] ?>themes/blue.css" rel="stylesheet" type="text/css" id="style_color" />
	<link href="<?php echo ASSETS['CSS'] ?>style-responsive.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo ASSETS['CSS'] ?>custom.css" rel="stylesheet" type="text/css" />
	<!-- END THEME STYLES -->
</head>
<!-- END HEAD -->

<!-- BEGIN BODY -->
<body>
	<!-- BEGIN TOP BAR -->
<div class="front-topbar">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6"></div>
                    <div class="col-md-6 col-sm-6">
                        <!-- <ul class="list-unstyled inline" style="margin-left: 365px;"> -->
                        <ul class="list-unstyled inline" style="margin-left: 433px;">
                            <li><a href="<?php echo GLOBAL_VARS['FACEBOOK'] ?>" target="_blank"><i class="icon-facebook"></i></a></li>
                            <li><a href="<?php echo GLOBAL_VARS['LINKEDIN'] ?>" target="_blank"><i class="icon-linkedin"></i></a></li>
                            <li class="sep"><span>|</span></li>
                        	<li><a href="/login" target="_blank">Log In</a></li>
                        </ul>
                    </div>
                </div>
            </div>        
        </div>
<!-- END TOP BAR -->
<!-- BEGIN HEADER -->
	<div class="header navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<!-- BEGIN RESPONSIVE MENU TOGGLER -->
				<button class="navbar-toggle btn navbar-btn" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<!-- END RESPONSIVE MENU TOGGLER -->
				<!-- BEGIN LOGO (you can use logo image instead of text)-->
				<a class="navbar-brand logo-v1" href="/"> 
					<img src="<?php echo ASSETS['IMG']?>logo-semhora.png" id="logoimg" alt="">
				</a>
				<!-- END LOGO -->
			</div>

			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown pagina_principal">
						<a class="dropdown-toggle" data-hover="dropdown" data-delay="0"
						data-close-others="false" href="/"> PÁGINA PRINCIPAL <!-- <i class="icon-angle-down"></i> --></a>
					</li>
				</ul>
			</div>
			<!-- BEGIN TOP NAVIGATION MENU -->
		</div>
	</div>
	<link rel="shortcut icon" href="<?php echo ASSETS['IMG']?>favicon.ico" />
	<!-- END HEADER -->

	<!-- BEGIN PAGE CONTAINER -->
	<div class="page-container">

		<!-- BEGIN CONTAINER -->
		<div class="container">
			<!-- BEGIN SERVICE BOX -->
			<div class="row service-box">
				<div class="col-md-4 col-sm-4">
					<div class="service-box-heading">
						<em>
							<i class="icon-location-arrow blue"></i> 
						</em> 
						<span>SEGURANÇA</span>
					</div>
					<p align="justify">
						Uma das principais características de nossos sistemas é o acesso 
						por meio da Internet. Por esse motivo, temos um cuidado especial
						com a Segurança da Informação. Todos os nossos produtos são submetidos
						a um rigoroso teste de segurança antes de serem publicados na Web, e
						são monitorados 24 horas por dia.  
					</p>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="service-box-heading">
						<em>
							<i class="icon-ok red"></i> 
						</em> 
						<span>DISPONIBILIDADE</span>
					</div>
					<p align="justify">
						Um requisito muito importante que deve ser observado no momento da
						escolha de um sistema para a sua empresa, é a disponibilidade. Os 
						nossos produtos estão hospedados em um ambiente preparado para funcionar
						de acordo com padrões internacionais. Todos os nossos servidores possuem 
						redundância, ou seja, em caso de falha de um, o outro assume imediatamente.
					</p>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="service-box-heading">
						<em>
							<i class="icon-resize-small green"></i> 
						</em> 
						<span>ESCALABILIDADE</span>
					</div>
					<p align="justify">
						Um sistema de qualidade deve estar preparado para crescer junto com
						a sua empresa. As nossas soluções foram desenvolvidas para serem
						escaláveis, ou seja, para suportar o aumento contínuo de utilização
						sem prejuizo ao seu negócio.
					</p>
				</div>
			</div>
			<!-- END SERVICE BOX -->

			<div class="clearfix"></div>
		</div>
		<!-- END CONTAINER -->
	</div>
	<!-- END PAGE CONTAINER -->

	<!-- BEGIN FOOTER -->
	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4 space-mobile">
					<!-- BEGIN ABOUT -->
					<h2>QUEM SOMOS</h2>
					<p align="justify" class="margin-bottom-30">
						O Sem Hora, empresa de tecnologia aplicada à eventos de entretenimento, 
						foi fundado em 2013 pelo CEO Luis Felipe Palomares. 
						Hoje a empresa é referência no segmento premium de entretenimento.
					</p>
					<div class="clearfix"></div>
					<!-- END ABOUT -->
				</div>
				<div class="col-md-4 col-sm-4 space-mobile">
					<!-- BEGIN CONTACTS -->
					<h2>CONTATO</h2>
					<div id='contatoFooter'>
						<address class="margin-bottom-40">
							<div id='campoEnderecoFooter'>
								Edifício: <?php echo GLOBAL_VARS['EDIFICIO'];?><br /> 
								Endereço: <?php echo GLOBAL_VARS['ENDERECO'];?><br />
							</div>
							<i class="icon-phone topbar-info-icon top-2"></i><span><div id='divNumTelefone'><?php echo GLOBAL_VARS['TELEFONE']; ?></div></span><br /> 
							<i class="icon-envelope-alt topbar-info-icon top-2"></i><a href="mailto:<?php echo GLOBAL_VARS['EMAIL'];?>"><div id='divEmailContato'><?php echo GLOBAL_VARS['EMAIL'];?></div></a>
						</address>
					</div>
					<!-- END CONTACTS -->
				</div>
				
				<div class="col-md-4 col-sm-4"></div>
			</div>
		</div>
	</div>
	<!-- END FOOTER -->

	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-sm-8">
					<p>
						<span class="margin-right-10">
							<?php echo date('Y'); ?> &copy; <?php echo GLOBAL_VARS['TITULO'] ?>
						</span> 
					</p>
				</div>
				<div class="col-md-4 col-sm-4">
					<ul class="social-footer">
						<li><a href="<?php echo GLOBAL_VARS['FACEBOOK'] ?>" target="_blank"><i class="icon-facebook"></i> </a></li>
						<li><a href="<?php echo GLOBAL_VARS['LINKEDIN'] ?>" target="_blank"><i class="icon-linkedin"></i> </a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- END COPYRIGHT -->

	<!-- Load javascripts at bottom, this will reduce page load time -->
	<!-- BEGIN $GLOBALS['CORE'] PLUGINS(REQUIRED FOR ALL PAGES) -->
	<!--[if lt IE 9]>
    <![endif]-->
	<script src="<?php echo ASSETS['PLUGINS'] ?>jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>hover-dropdown.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>back-to-top.js" type="text/javascript"></script>
	<!-- END $GLOBALS['CORE'] PLUGINS -->

	<!-- BEGIN PAGE LEVEL JAVASCRIPTS(REQUIRED ONLY FOR CURRENT PAGE) -->
	<script src="<?php echo ASSETS['PLUGINS'] ?>fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>revolution_slider/rs-plugin/js/jquery.themepunch.plugins.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>revolution_slider/rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>bxslider/jquery.bxslider.min.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['PLUGINS'] ?>blockUI/jquery.blockUI.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['SCRIPTS'] ?>app.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['SCRIPTS'] ?>index.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['SCRIPTS'] ?>custom.js" type="text/javascript"></script>
	<script src="<?php echo ASSETS['SCRIPTS'] ?>footer.js" type="text/javascript"></script>
					
	<script type="text/javascript">
	$(document).ajaxStop($.unblockUI);
	
	jQuery(document).ready(function() {
		ControleMenuAtivo('pagina_principal');
		App.init();
	});
	</script>
	<!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>